// Country -> search terms for finding restaurants of that cuisine in OpenStreetMap.
// The first term is also used to match restaurant names ("Hungarian Kitchen").
// OSM cuisine tags are lowercase and use underscores for spaces ("sri_lankan").

const CUISINES = {
    'Afghanistan': ['afghan'], 'Albania': ['albanian'], 'Algeria': ['algerian'], 'Andorra': ['andorran', 'catalan'],
    'Angola': ['angolan'], 'Antigua and Barbuda': ['antiguan', 'caribbean'], 'Argentina': ['argentinian', 'argentine', 'argentinean'],
    'Armenia': ['armenian'], 'Australia': ['australian'], 'Austria': ['austrian'], 'Azerbaijan': ['azerbaijani', 'azeri'],
    'Bahamas': ['bahamian', 'caribbean'], 'Bahrain': ['bahraini'], 'Bangladesh': ['bangladeshi', 'bengali'],
    'Barbados': ['barbadian', 'bajan', 'caribbean'], 'Belarus': ['belarusian'], 'Belgium': ['belgian'], 'Belize': ['belizean'],
    'Benin': ['beninese'], 'Bhutan': ['bhutanese'], 'Bolivia': ['bolivian'], 'Bosnia and Herzegovina': ['bosnian'],
    'Botswana': ['botswanan', 'tswana'], 'Brazil': ['brazilian'], 'Brunei': ['bruneian'], 'Bulgaria': ['bulgarian'],
    'Burkina Faso': ['burkinabe'], 'Burundi': ['burundian'], 'Cabo Verde': ['cape verdean', 'cabo verde'],
    'Cambodia': ['cambodian', 'khmer'], 'Cameroon': ['cameroonian'], 'Canada': ['canadian', 'poutine'],
    'Central African Republic': ['central african'], 'Chad': ['chadian'], 'Chile': ['chilean'], 'China': ['chinese'],
    'Colombia': ['colombian'], 'Comoros': ['comorian'], 'Congo': ['congolese'], 'DR Congo': ['congolese'],
    'Costa Rica': ['costa rican'], 'Croatia': ['croatian'], 'Cuba': ['cuban'], 'Cyprus': ['cypriot'], 'Czechia': ['czech'],
    'Denmark': ['danish'], 'Djibouti': ['djiboutian'], 'Dominica': ['dominica'], 'Dominican Republic': ['dominican'],
    'Ecuador': ['ecuadorian', 'ecuadorean'], 'Egypt': ['egyptian'], 'El Salvador': ['salvadoran', 'salvadorian'],
    'Equatorial Guinea': ['equatoguinean'], 'Eritrea': ['eritrean'], 'Estonia': ['estonian'], 'Eswatini': ['swazi'],
    'Ethiopia': ['ethiopian'], 'Fiji': ['fijian'], 'Finland': ['finnish'], 'France': ['french'], 'Gabon': ['gabonese'],
    'Gambia': ['gambian'], 'Georgia': ['georgian'], 'Germany': ['german'], 'Ghana': ['ghanaian'], 'Greece': ['greek'],
    'Grenada': ['grenadian'], 'Guatemala': ['guatemalan'], 'Guinea': ['guinean'], 'Guinea-Bissau': ['guinea-bissau', 'bissau'],
    'Guyana': ['guyanese'], 'Haiti': ['haitian'], 'Honduras': ['honduran'], 'Hungary': ['hungarian'], 'Iceland': ['icelandic'],
    'India': ['indian'], 'Indonesia': ['indonesian'], 'Iran': ['iranian', 'persian'], 'Iraq': ['iraqi'], 'Ireland': ['irish'],
    'Israel': ['israeli'], 'Italy': ['italian'], 'Jamaica': ['jamaican'], 'Japan': ['japanese'], 'Jordan': ['jordanian'],
    'Kazakhstan': ['kazakh'], 'Kenya': ['kenyan'], 'Kiribati': ['kiribati'], 'North Korea': ['north korean'],
    'South Korea': ['korean'], 'Kuwait': ['kuwaiti'], 'Kyrgyzstan': ['kyrgyz'], 'Laos': ['lao', 'laotian'], 'Latvia': ['latvian'],
    'Lebanon': ['lebanese'], 'Lesotho': ['basotho', 'lesotho'], 'Liberia': ['liberian'], 'Libya': ['libyan'],
    'Liechtenstein': ['liechtenstein'], 'Lithuania': ['lithuanian'], 'Luxembourg': ['luxembourgish', 'luxembourg'],
    'Madagascar': ['malagasy', 'madagascan'], 'Malawi': ['malawian'], 'Malaysia': ['malaysian'], 'Maldives': ['maldivian'],
    'Mali': ['malian'], 'Malta': ['maltese'], 'Marshall Islands': ['marshallese'], 'Mauritania': ['mauritanian'],
    'Mauritius': ['mauritian'], 'Mexico': ['mexican'], 'Micronesia': ['micronesian'], 'Moldova': ['moldovan'],
    'Monaco': ['monegasque', 'monaco'], 'Mongolia': ['mongolian'], 'Montenegro': ['montenegrin'], 'Morocco': ['moroccan'],
    'Mozambique': ['mozambican'], 'Myanmar': ['burmese', 'myanmar'], 'Namibia': ['namibian'], 'Nauru': ['nauruan'],
    'Nepal': ['nepalese', 'nepali'], 'Netherlands': ['dutch'], 'New Zealand': ['new zealand', 'kiwi'], 'Nicaragua': ['nicaraguan'],
    'Niger': ['nigerien'], 'Nigeria': ['nigerian'], 'North Macedonia': ['macedonian'], 'Norway': ['norwegian'], 'Oman': ['omani'],
    'Pakistan': ['pakistani'], 'Palau': ['palauan'], 'Palestine': ['palestinian'], 'Panama': ['panamanian'],
    'Papua New Guinea': ['papua new guinea', 'papuan'], 'Paraguay': ['paraguayan'], 'Peru': ['peruvian'],
    'Philippines': ['filipino', 'philippine'], 'Poland': ['polish'], 'Portugal': ['portuguese'], 'Qatar': ['qatari'],
    'Romania': ['romanian'], 'Russia': ['russian'], 'Rwanda': ['rwandan'], 'Saint Kitts and Nevis': ['kittitian', 'st kitts'],
    'Saint Lucia': ['saint lucian', 'st lucia'], 'Saint Vincent and the Grenadines': ['vincentian', 'st vincent'],
    'Samoa': ['samoan'], 'San Marino': ['sammarinese', 'san marino'], 'Sao Tome and Principe': ['sao tome', 'são tomé'],
    'Saudi Arabia': ['saudi'], 'Senegal': ['senegalese'], 'Serbia': ['serbian'], 'Seychelles': ['seychellois', 'seychelles'],
    'Sierra Leone': ['sierra leonean', 'sierra leone'], 'Singapore': ['singaporean'], 'Slovakia': ['slovak'],
    'Slovenia': ['slovenian', 'slovene'], 'Solomon Islands': ['solomon'], 'Somalia': ['somali'], 'South Africa': ['south african'],
    'South Sudan': ['south sudanese'], 'Spain': ['spanish', 'tapas'], 'Sri Lanka': ['sri lankan'], 'Sudan': ['sudanese'],
    'Suriname': ['surinamese'], 'Sweden': ['swedish'], 'Switzerland': ['swiss'], 'Syria': ['syrian'], 'Taiwan': ['taiwanese'],
    'Tajikistan': ['tajik'], 'Tanzania': ['tanzanian'], 'Thailand': ['thai'], 'Timor-Leste': ['timorese'], 'Togo': ['togolese'],
    'Tonga': ['tongan'], 'Trinidad and Tobago': ['trinidadian', 'trini'], 'Tunisia': ['tunisian'], 'Türkiye': ['turkish'],
    'Turkmenistan': ['turkmen'], 'Tuvalu': ['tuvaluan'], 'Uganda': ['ugandan'], 'Ukraine': ['ukrainian'],
    'United Arab Emirates': ['emirati'], 'United Kingdom': ['british'], 'United States': ['american'], 'Uruguay': ['uruguayan'],
    'Uzbekistan': ['uzbek'], 'Vanuatu': ['vanuatu'], 'Vatican City': ['vatican'], 'Venezuela': ['venezuelan'],
    'Vietnam': ['vietnamese'], 'Yemen': ['yemeni'], 'Zambia': ['zambian'], 'Zimbabwe': ['zimbabwean']
};

module.exports = { CUISINES };
